List names = [
  'Ochako Uraraka',
  'Mouysser Alsaeed',
  'Omar Al-Saeed',
  'Nagham Azzam',
  'Rama Bannour',
  'Abd AlRahman',
  'Lionel Messi',
  'Max Verstappen',
  'Izuku Midoryia',
  'Lilian Kaboul',
  'Mom',
  'Dad',
  'Dr. Raghad',
  'Roaa',
  'WorkPlace',
];

List images = [
  'images/zzzz.jpg',
  'images/me.jpg',
  'images/baby.jpg',
  'images/nagham.jpg',
  'images/flower1.jpg',
  'images/car.png',
  'images/messi.jpg',
  'images/max.jpg',
  'images/izuku.jpg',
  'images/flower2.jpg',
  'images/flower3.jpg',
  'images/sky.jpg',
  'images/raghad.jpg',
  'images/Roaa.jpg',
  'images/ite.jpg',
];

List messages = [
  'Hope you\'re doing okay ^^',
  'I am TEH BESTO',
  'go go gagaaa where milk?',
  'Sorry I was asleep XD',
  'See you soon!',
  'GG WP Bro',
  'King, need a new logo plz',
  'MAX MAX MAX SUPER MAX MAX',
  'Wait BRB there\'s some villian here I\'ll take care of \'em',
  'I\'m also working on a chat app in flutter! What a coincidence :D',
  'We need milk for Omar get some with you',
  'Aloooooo',
  'archive.zip',
  'HEEEELP ERROR BIGGER THAN MY FACE!!1!',
  'Where are you?',
];

List times = [
  '5:32 AM',
  '7:12 PM',
  '2:16 AM',
  '9:55 PM',
  '11:21 PM',
  '1:35 AM',
  '4:31 AM',
  '11:55 PM',
  '9:33 PM',
  '8:47 PM',
  '3:02 PM',
  '12:31 PM',
  '11:11 AM',
  '6:15 PM',
  '7:30 AM'
];
